### ISSUE TITLE
Inclusion in Flathub repository

### ISSUE THREAD

**Issue by milouse** [ghostery/flathub#1]
This repository is only needed for initial submission. As per [Flathub Submission Process](https://docs.flathub.org/docs/for-app-authors/submission/), once we will be added to their repository, they will open a new repository for us under the Flathub github organisation. Thus this very repository will not last very long.

That said, we need to check that everything is ok before actually submitting the new app.

```[tasklist]
### Tasks
- [ ] Check that we are fine with the [metainfo brand content](https://github.com/ghostery/flathub/blob/com.ghostery.browser/com.ghostery.browser.metainfo.xml)
- [ ] Identify who should open the PR upstream, as it will be probably the one invited to join the Flathub org in the first place. (@chrmod ?). 
- [ ] Once the app is published on flathub, go [trough the verification process](https://docs.flathub.org/docs/for-app-authors/verification) (@milouse). I might need support at this point following what data they need for the validation to occur.
- [ ] Check whether we can block auto-update by masquerading some user_prefs instead of relying on Firefox Policies (@milouse)
```

**Comment by milouse** [comment]
Auto update desactivated through release channel masquerading
